### ISSUE TITLE
Error adding Lovelace card in UI or YAML mode.

### ISSUE THREAD

**Issue by bgunsberger** [sgttrs/lovelace-weather-card-chart#31]
Hi, I followed the instructions in the Readme, but after a restart, I'm getting:

 "Error: Custom element not found: weather-card-chart"

when trying to add the card in UI or YAML mode. 

I definitely have the latest .js file uploaded to config/www. using:

> wget https://raw.githubusercontent.com/sgttrs/lovelace-weather-card-chart/master/weather-card-chart.js

Thanks.

**Comment by MarcusUA** [comment]
hey,
did you add it as 'url: /local/**custom**-weather-card-chart.js' or 'url: /local/weather-card-chart.js'
Readme has incorrect file name.

**Comment by bgunsberger** [comment]
Great catch! I should have noticed that. Thanks!
