### ISSUE TITLE
Day Labels Wrong

### ISSUE THREAD

**Issue by wixoff** [sgttrs/lovelace-weather-card-chart#5]
I'm using this custom card with `weather.dark_sky`, and I think the day labels at the top of the chart are wrong, i.e. the labels are behind by one day.

As I write this it's Monday, and the first label says "Sun" and the temperatures and precipitation seem to match up with today.

Similarly, the second label says "Mon" but the temperature in particular looks like Tuesday's - it's supposed to warm up quite a bit tomorrow.

Not sure what else I can add - my configuration is minimal: `mode: daily` is the only customization I have added.

**Comment by sgttrs** [comment]
Hello. Are you sure that you are using the latest version of the card? Which browser has this issue?

**Comment by soundwave12345** [comment]
Same here. Days are shifted by one

**Comment by wixoff** [comment]
I noticed it in the HA iOS app.  I'm not sure what the version of the card is, but I installed it more recently than the last commits to the repo.

There's also a comment on the HA Community board about this same issue: 

https://community.home-assistant.io/t/lovelace-weather-card-with-chart/88816/41

**Comment by e-krebs** [comment]
days are showing fine for me.

**Comment by wixoff** [comment]
I'll cross-reference https://github.com/home-assistant/home-assistant/issues/23166 which appears to confirm that the issue is with the underlying weather platform, not this Lovelace card.  Closing.
