### ISSUE TITLE
Wind Direction ICONs seems to be inverted!

### ISSUE THREAD

**Issue by papperone** [sgttrs/lovelace-weather-card-chart#6]
I noticed that arrows for wind direction are swapped:
when direction is "N" arrow is pointing down
when direction is "SE" arrow is poiting up/left
and so on...

is it me or arrow icons direction should be fixed?

**Comment by e-krebs** [comment]
same for E-NE which is poinging down-left

**Comment by sgttrs** [comment]
From Wikipedia: 

> Wind direction is reported by the direction from which it originates. For example, a northerly wind blows from the north to the south.

https://en.wikipedia.org/wiki/Wind_direction
